/* Generated By:JavaCC: Do not edit this line. AsmParserConstants.java */
package de.tum.mocca.parser;

public interface AsmParserConstants {

  int EOF = 0;
  int SPC = 1;
  int LETTER = 2;
  int DIGIT = 3;
  int HEX = 4;
  int PROC = 6;
  int SINGLE_LINE_COMMENT = 7;
  int DATA = 10;
  int ENDP = 11;
  int EOL = 12;
  int COMMA = 13;
  int ASSIGN = 14;
  int LPAREN = 15;
  int RPAREN = 16;
  int LABEL = 17;
  int HEXLITERAL = 18;
  int DECLITERAL = 19;
  int ADDRESS = 20;
  int INSTPREFIX = 21;
  int PTRPREFIX = 22;
  int SHORT = 23;
  int FAR = 24;
  int SMALL = 25;
  int LARGE = 26;
  int OFFSET = 27;
  int IDENTIFIER = 28;

  int InsideProc = 0;
  int DEFAULT = 1;

  String[] tokenImage = {
    "<EOF>",
    "<SPC>",
    "<LETTER>",
    "<DIGIT>",
    "<HEX>",
    "<token of kind 5>",
    "<PROC>",
    "<SINGLE_LINE_COMMENT>",
    "\" \"",
    "\"\\t\"",
    "<DATA>",
    "\"endp\"",
    "<EOL>",
    "\",\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "<LABEL>",
    "<HEXLITERAL>",
    "<DECLITERAL>",
    "<ADDRESS>",
    "<INSTPREFIX>",
    "<PTRPREFIX>",
    "\"short\"",
    "\"far\"",
    "\"small\"",
    "\"large\"",
    "\"offset\"",
    "<IDENTIFIER>",
  };

}
