/* Generated By:JJTree&JavaCC: Do not edit this line. CtplParserConstants.java */
package de.tum.mocca.parser;

public interface CtplParserConstants {

  int EOF = 0;
  int EOL = 3;
  int SPC = 4;
  int LPARENT = 5;
  int RPARENT = 6;
  int COMMA = 7;
  int ALL = 8;
  int FINALLY = 9;
  int EXISTS = 10;
  int NEXT = 11;
  int GLOBALLY = 12;
  int UNTIL = 13;
  int AND = 14;
  int OR = 15;
  int NOT = 16;
  int QEXISTS = 17;
  int LETTER = 18;
  int DIGIT = 19;
  int PREDICATE = 20;
  int VARIABLE = 21;
  int IDENTIFIER = 22;

  int WithinPredicate = 0;
  int DEFAULT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<EOL>",
    "<SPC>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"A\"",
    "\"F\"",
    "\"E\"",
    "\"X\"",
    "\"G\"",
    "\"U\"",
    "\"&\"",
    "\"|\"",
    "\"-\"",
    "\"exists\"",
    "<LETTER>",
    "<DIGIT>",
    "<PREDICATE>",
    "<VARIABLE>",
    "<IDENTIFIER>",
  };

}
