/* Generated By:JJTree: Do not edit this line. de/tum/mocca/parser/\CtplParserTreeConstants.java */

package de.tum.mocca.parser;

public interface CtplParserTreeConstants
{
  public int JJTONELINE = 0;
  public int JJTVOID = 1;
  public int JJTOR = 2;
  public int JJTAND = 3;
  public int JJTAU = 4;
  public int JJTEU = 5;
  public int JJTAX = 6;
  public int JJTAF = 7;
  public int JJTAG = 8;
  public int JJTEX = 9;
  public int JJTEF = 10;
  public int JJTEG = 11;
  public int JJTEXISTS = 12;
  public int JJTNOT = 13;
  public int JJTPREDICATE = 14;
  public int JJTPARAMETER = 15;
  public int JJTVARIABLE = 16;


  public String[] jjtNodeName = {
    "oneline",
    "void",
    "or",
    "and",
    "AU",
    "EU",
    "AX",
    "AF",
    "AG",
    "EX",
    "EF",
    "EG",
    "exists",
    "not",
    "predicate",
    "parameter",
    "variable",
  };
}
