[version]
Mocca 0.1

[name]
Macro CopySelf

[description]
Autogenerated CopySelf specification.
The executable retrieves its own filename and uses this information to copy itself
to a different location. More general than the manual version, it allows
indirect and direct parameter initialization.

[clues]
call(CopyFileA)
call(GetModuleFileNameA)

[formula]
EF(%syscall(GetModuleFileNameA, $*, $pFile, 0) & E %noassign($pFile) U %syscall(CopyFileA, $pFile))
